server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        label: master
        git:
          uri: https://github.com/endend20000/cloud.git
          searchPaths: cloud/resources/
          username: endend20000
          password: homeend724
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/